version: '3'
services:
  client-mongo:
    image: mongoclient/mongoclient
    restart: always
    depends_on:
      - db-quant
    links:
      - db-quant:db
    networks:
      frontend_quant:
      backend_quant:
    ports:
      - "10.1.1.99:3000:3000/tcp"
    volumes:
      - volume-quant-mongo-client:/data/db
    environment:
      MONGO_URL: "mongodb://db-quant"
      MONGOCLIENT_DEFAULT_CONNECTION_URL: "mongodb://db-quant"

  db-quant:
    image: mongo:3.4.4
    restart: always
    networks:
      backend_quant:
    ports:
      - "27017:27017/tcp"
    volumes:
      - volume-quant-db-data:/data/db
      - volume-quant-db-config:/data/configdb

networks:
  frontend_quant:
  backend_quant:

volumes:
  volume-quant-db-data:
  volume-quant-db-config:
  volume-quant-mongo-client:
